-package name: Numpy

-Numpy means numerical python

-it is similar to math pacakage

-it completely focus on math operations

-mean-median-mode-varainace-covarience

-distance between to points

-linear algebra

-matrixs operations etc

- When its comes storing a numbers

- list and tuple

- array:numpy

-tensors:tensorflow or pytorch




In [6]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[]
for (i,j) in zip(l1,l2):
    l.append(i+j)
l

[11, 22, 33, 44]

In [8]:
l=[i+j for i,j in zip(l1,l2)]
l

[11, 22, 33, 44]

In [10]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l1+l2

[10, 20, 30, 40, 1, 2, 3, 4]

In [24]:
import numpy as np
l1=[10,20,30,40]
arr1=np.array(l1)

In [18]:
import time
start=time.time()
l1=list(range(1,1000000))
l2=list(range(1,1000000))
mul=[i*j for i,j in zip(l1,l2)]
end=time.time()
print(end-start)

0.29865479469299316


In [20]:
import time
start=time.time()
arr1=np.arange(1,1000000)
arr2=np.arange(1,1000000)
mul=arr1*arr2
end=time.time()
print(end-start)

0.02562737464904785


- Always question yourself

   - How can we do vector operations

   - How can we do matrix operations

   - How can we do linera algebra operations

   - Then the answer is Numpy

- Is Numpy elements represents in arrays

- every array as dimension 


In [4]:
import numpy as np
l1=[30,40,50]
arr1=np.array(l1)
arr1

array([30, 40, 50])

In [6]:
import numpy as np
l1=[30,40,50]
arr1=np.array(l1)
arr1.ndim

1

In [12]:
import numpy as np
l1=[30,40,50]
arr1=np.array(l1)
arr1.shape

(3,)

In [10]:
import numpy as np
l1=[30,40,50]
arr1=np.array(l1)
arr1.size

3

In [16]:
import numpy  as np
l1=[10,20,30,40]
l2=[1,2,3,4]
arr2d=np.array([l1,l2])
arr2d

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [18]:
arr2d.ndim

2

In [20]:
arr2d.shape

(2, 4)

In [22]:
arr2d.size

8

In [24]:
import numpy  as np
l1=[10,20,30,40]
l2=[1,2,3,4]
arr3d=np.array([[l1,l2]])
arr3d

array([[[10, 20, 30, 40],
        [ 1,  2,  3,  4]]])

In [26]:
arr3d.ndim

3

In [28]:
arr3d.shape

(1, 2, 4)

In [30]:
arr2d.size

8

l.m.n: 2,2,4

- -n indicates how many elements we have in a list

    -n=4 means a list has 4 elements :[10,20,30,40]

- m indicates how many lists avaiable 

    -m=2 means 2 lists are avaiable

    each list how many 4 values

    one list name is :l1

    another list name is : l2

    m:[l1,l2]
- l indicates how many m

   -l=2 means there are 2 m's avaiable

   -m=[l1,l2]

   -[[l1,l2],[l1,l2]]

In [33]:
l1=[10,20,30,40]
l2=[1,2,3,4]
np.array([[l1,l2],[l1,l2]])

array([[[10, 20, 30, 40],
        [ 1,  2,  3,  4]],

       [[10, 20, 30, 40],
        [ 1,  2,  3,  4]]])

In [35]:
np.array([[l1,l2],[l1,l2]]).shape

(2, 2, 4)

In [43]:
l1=[10,20,30,40]
np.array([l1,l1]).shape

(2, 4)

In [47]:
l1=[10,20,30,40]
l2=[1,2,3,4]
np.array([[l1,l2],[l1,l2],[l1,l2]]).shape

(3, 2, 4)

In [75]:
l1=[10,20,30,40]
l2=[1,2,3,4]
m=[l1,l2]
k=[l,l,l,l]
n=[k,k,k,k,k]
np.array(n).shape


(5, 4, 3, 4)

In [81]:
l1=[10,20,30,40]
h1=[[l1,l1,l1],[l1,l1,l1],[l1,l1,l1]]
np.array(h1).shape


(3, 3, 4)

In [83]:
shape=(3,3)
np.zeros(shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
shape=(3,3)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
shape=(3,3)
np.ones(shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
arr11=np.eye(4)
arr11

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
arr11.flatten()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [111]:
arr11.flatten().tolist()

[1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0]

In [113]:
arr11.transpose()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
import random
random.randint(10,20)

17

In [3]:
import numpy as np
np.random.randint(10)

7

In [5]:
np.random.randint(10,50)

28

In [7]:
np.random.randint(10,50,size=5)

array([30, 44, 47, 28, 32])

In [9]:
shape=(2,3)
np.random.randint(10,50,size=shape)

array([[44, 28, 17],
       [45, 25, 19]])

- when we develop ML models we use some date for training some data for testing
 
- also we will use multiple models for traing and testing

- Out of these models which model gives best results that we selected
 
- so we need every model should test on same data
  
- this we can achieve by **np.random.seed()**

In [19]:
np.random.seed(1234)
np.random.randint(10,15,size=5)

array([13, 14, 14, 10, 11])